name: Deploy Backend to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Spring Boot JAR
        run: |
          cd customer-directory-spring-boot
          ./gradlew clean build -x test
          mkdir -p deploy
          cp build/libs/*.jar deploy/application.jar
          cd deploy
          zip -r application.zip application.jar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        run: |
          EB_APP_NAME=${{ secrets.EB_APP_NAME }}
          EB_ENV_NAME=${{ secrets.EB_ENV_NAME }}
          VERSION_LABEL=github-${{ github.sha }}

          aws elasticbeanstalk create-application-version \
            --application-name $EB_APP_NAME \
            --version-label $VERSION_LABEL \
            --source-bundle ApplicationName=$EB_APP_NAME,VersionLabel=$VERSION_LABEL,SourceBundle={"S3Bucket":"none","S3Key":"none"} \
            --auto-create-application

          aws elasticbeanstalk update-environment \
            --environment-name $EB_ENV_NAME \
            --version-label $VERSION_LABEL
